// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class CoaMaster
{
    public int CoaId { get; set; }

    public string CoaNo { get; set; }

    public string CoaName { get; set; }

    public bool? IsActive { get; set; }
}