// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class Erpcustomer
{
    public int CustId { get; set; }

    public string CustNo { get; set; }

    public string CustName { get; set; }

    public string CustName2 { get; set; }

    public string CustAddress { get; set; }

    public string CustAddress2 { get; set; }

    public string City { get; set; }

    public string Contact { get; set; }

    public string PinCode { get; set; }

    public string StateCode { get; set; }

    public string CountryRegionCode { get; set; }

    public string GstregistrationNo { get; set; }

    public string GstcustomerType { get; set; }

    public string PanNo { get; set; }

    public string Email { get; set; }

    public string PrimaryContactNo { get; set; }
}