// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImpiLine
{
    public int ImpiLineId { get; set; }

    public string ImpiLinePiNo { get; set; }

    public string ImpiLineDescription { get; set; }

    public decimal ImpiLineQuantity { get; set; }

    public decimal ImpiLineUnitPrice { get; set; }

    public decimal ImpiLineDiscount { get; set; }

    public decimal ImpiLineAmount { get; set; }

    public bool ImpiLineActive { get; set; }

    public string ImpiLineCreatedBy { get; set; }

    public DateTime ImpiLineCreatedOn { get; set; }

    public string ImpiLineModifiedBy { get; set; }

    public DateTime? ImpiLineModifiedOn { get; set; }

    public int? PiHeaderId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FicciImpiHeader PiHeader { get; set; }
}