// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImm
{
    public int ImmsId { get; set; }

    public string ImmsCode { get; set; }

    public string ImmsValue { get; set; }

    public string ImmsCategory { get; set; }

    public bool ImmsActive { get; set; }

    public string ImmsCreatedBy { get; set; }

    public DateTime ImmsCreatedOn { get; set; }

    public string ImmsModifiedBy { get; set; }

    public DateTime? ImmsModifiedOn { get; set; }
}