// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImem
{
    public int ImemId { get; set; }

    public string ImemEmpid { get; set; }

    public string ImemName { get; set; }

    public DateTime ImemJoiningDate { get; set; }

    public string ImemDesignation { get; set; }

    public string ImemDepartment { get; set; }

    public string ImemLocation { get; set; }

    public string ImemEmail { get; set; }

    public string ImemWorkLevel { get; set; }

    public string ImemManagerId { get; set; }

    public string ImemManagerEmail { get; set; }

    public string ImemClusterId { get; set; }

    public string ImemClusterEmail { get; set; }

    public string ImemDepartmentHeadId { get; set; }

    public string ImemDepartmentHeadEmail { get; set; }

    public bool? ImemActive { get; set; }

    public string ImemCreatedBy { get; set; }

    public DateTime ImemCreatedOn { get; set; }

    public string ImemModifiedBy { get; set; }

    public DateTime? ImemModifiedOn { get; set; }

    public string ImemEmploymentType { get; set; }

    public string ImemUsername { get; set; }
}