// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using FICCI_API.ModelsEF;

namespace FICCI_API.ModelsEF
{
    public partial class FICCI_DB_APPLICATIONSContext
    {

        [DbFunction("FICCI_GETPINUMBERSEQ", "dbo")]
        public static string FICCI_GETPINUMBERSEQ()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
