// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImad
{
    public int ImadId { get; set; }

    public string ImadRecordNo { get; set; }

    public string ImadScreenName { get; set; }

    public string ImadFileName { get; set; }

    public string ImadFileType { get; set; }

    public string ImadFileSize { get; set; }

    public string ImadFileUrl { get; set; }

    public bool ImadActive { get; set; }

    public string ImadCreatedBy { get; set; }

    public DateTime ImadCreatedOn { get; set; }

    public string ImadModifiedBy { get; set; }

    public DateTime? ImadModifiedOn { get; set; }

    public int? ResourceId { get; set; }

    public string ResourceType { get; set; }

    public int? ResourceTypeId { get; set; }

    public string TypeOfAttachment { get; set; }
}