// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImpiLine
{
    public int ImpiLineId { get; set; }

    public int? PiHeaderId { get; set; }

    public string ImpiLinePiNo { get; set; }

    public string ImpiDocumentNo { get; set; }

    public string ImpiLineNo { get; set; }

    public string DocumentType { get; set; }

    public string ImpiGlNo { get; set; }

    public string ImpiLocationCode { get; set; }

    public string ImpiQuantity { get; set; }

    public decimal? ImpiUnitPrice { get; set; }

    public decimal? ImpiLineAmount { get; set; }

    public string ImpiGstgroupCode { get; set; }

    public string ImpiGstgroupType { get; set; }

    public string ImpiHsnsaccode { get; set; }

    public string ImpiType { get; set; }

    public decimal? ImpiGstBaseAmount { get; set; }

    public decimal? ImpiNetTotal { get; set; }

    public decimal? ImpiTotalGstAmount { get; set; }

    public bool ImpiLineActive { get; set; }

    public bool IsDeleted { get; set; }

    public string ImpiLineCreatedBy { get; set; }

    public DateTime ImpiLineCreatedOn { get; set; }

    public string ImpiLineModifiedBy { get; set; }

    public DateTime? ImpiLineModifiedOn { get; set; }

    public virtual FicciImpiHeader PiHeader { get; set; }
}