// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImum
{
    public int ImumId { get; set; }

    public string ImumEmpid { get; set; }

    public string ImumUserid { get; set; }

    public string ImumPassword { get; set; }

    public string ImumName { get; set; }

    public string ImumRole { get; set; }

    public string ImumEmail { get; set; }

    public bool ImumActive { get; set; }

    public string ImumCreatedBy { get; set; }

    public DateTime ImumCreatedOn { get; set; }

    public string ImumModifiedBy { get; set; }

    public DateTime? ImumModifiedOn { get; set; }

    public string UserName { get; set; }

    public int RoleId { get; set; }

    public bool? IsDelete { get; set; }

    public virtual TblFicciRole Role { get; set; }
}