// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImmd
{
    public int ImmdId { get; set; }

    public string ImmdPiNo { get; set; }

    public string ImmdMailTo { get; set; }

    public string ImmdMailCc { get; set; }

    public string ImmdMailSubject { get; set; }

    public string ImmdMailBody { get; set; }

    public DateTime? ImmdMailSentOn { get; set; }

    public string ImmdMailRemarks { get; set; }

    public string ImmdMailAttachmentFileName { get; set; }

    public bool ImmdActive { get; set; }

    public string ImmdCreatedBy { get; set; }

    public DateTime ImmdCreatedOn { get; set; }

    public string ImmdModifiedBy { get; set; }

    public DateTime? ImmdModifiedOn { get; set; }

    public string ResourceType { get; set; }

    public int? ResourceId { get; set; }

    public bool? IsSent { get; set; }
}