// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciImwd
{
    public int ImwdId { get; set; }

    public string ImwdScreenName { get; set; }

    public string ImwdInitiatedBy { get; set; }

    public string ImwdRole { get; set; }

    public string ImwdRemarks { get; set; }

    public string ImwdStatus { get; set; }

    public string ImwdPendingAt { get; set; }

    public string ImwdCreatedBy { get; set; }

    public DateTime ImwdCreatedOn { get; set; }

    public int? CustomerId { get; set; }

    public int? ImwdType { get; set; }

    public string ImwdPendingEmailAt { get; set; }
}