// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class GstCustomerType
{
    public int CustomerTypeId { get; set; }

    public string CustomerTypeName { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDelete { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual ICollection<FicciErpCustomerDetail> FicciErpCustomerDetails { get; set; } = new List<FicciErpCustomerDetail>();
}