// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class Gstgroup
{
    public int GroupId { get; set; }

    public string GroupCode { get; set; }

    public bool? IsActive { get; set; }
}