// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class Hsnsac
{
    public int HsnId { get; set; }

    public string HsnCode { get; set; }

    public string HsnGroup { get; set; }
}