// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FICCI_API.ModelsEF;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FICCI_API.ModelsEF
{
    public partial interface IFICCI_DB_APPLICATIONSContextProcedures
    {
        Task<int> Backup_FICCI_DatabaseAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Approval_CustomerResult>> prc_Approval_CustomerAsync(string CustomerId, bool? IsApprove, string LoginId, int? statusid, string Remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Approval_InvoiceResult>> prc_Approval_InvoiceAsync(string HeaderId, bool? IsApprove, string LoginId, int? statusid, string Remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Configuration_DeleteResult>> prc_Configuration_DeleteAsync(int? C_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Configuration_DetailResult>> prc_Configuration_DetailAsync(int? C_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Configuration_FormResult>> prc_Configuration_FormAsync(bool? IsUpdate, int? C_ID, string C_Code, string C_Value, int? CategoryID, string User, bool? IsActive, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Configuration_listResult>> prc_Configuration_listAsync(int? C_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_drp_categorylistResult>> prc_drp_categorylistAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_EmployeeMaster_listResult>> prc_EmployeeMaster_listAsync(int? IMEM_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_FICCI_IMUM_listResult>> prc_FICCI_IMUM_listAsync(int? IMUM_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_Role_listResult>> prc_Role_listAsync(int? Role_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> prc_Truncate_tableAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_UserMaster_DeleteResult>> prc_UserMaster_DeleteAsync(int? IMUM_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_UserMaster_FormResult>> prc_UserMaster_FormAsync(bool? IsUpdate, string IMUM_EMPID, int? IMUM_ID, string IMUM_NAME, string IMUM_EMAIL, int? RoleID, bool? IMUM_ACTIVE, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
