// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class PostCode
{
    public int PostCodeId { get; set; }

    public string PostCode1 { get; set; }

    public string City { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDelete { get; set; }

    public DateTime? CreateDate { get; set; }
}