// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_FICCI_IMUM_listResult
    {
        public int IMUM_ID { get; set; }
        public string IMUM_EMPID { get; set; }
        public string IMUM_NAME { get; set; }
        public string IMUM_EMAIL { get; set; }
        public string Role_name { get; set; }
        public string UserName { get; set; }
        public bool IMUM_ACTIVE { get; set; }
    }
}
