// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_Approval_CustomerResult
    {
        public int returncode { get; set; }
        public string Message { get; set; }
        [Column("Initiated By")]
        public string InitiatedBy { get; set; }
        public string Status { get; set; }
        [Column("Customer Id")]
        public string CustomerId { get; set; }
    }
}
