// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_Role_listResult
    {
        public int Role_Id { get; set; }
        public string Role_name { get; set; }
        public string IsActive { get; set; }
    }
}
