// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_EmployeeMaster_listResult
    {
        public int IMEM_ID { get; set; }
        public string IMEM_EMPID { get; set; }
        public string IMEM_NAME { get; set; }
        public string IMEM_EMAIL { get; set; }
        public string IMEM_USERNAME { get; set; }
        public bool IMEM_ACTIVE { get; set; }
    }
}
