// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_Configuration_DetailResult
    {
        public string C_Code { get; set; }
        public string C_Value { get; set; }
        public int CategoryID { get; set; }
        public string IsActive { get; set; }
    }
}
