// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FICCI_API.ModelsEF
{
    public partial class prc_drp_categorylistResult
    {
        public int Id { get; set; }
        public string Category_Name { get; set; }
    }
}
