// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class TblConfigurationMaster
{
    public int Id { get; set; }

    public string CCode { get; set; }

    public string CValue { get; set; }

    public int CategoryId { get; set; }

    public string Createdby { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public virtual TblCategoryList Category { get; set; }
}