// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class TblCategoryList
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public string Createdby { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDelete { get; set; }

    public virtual ICollection<TblConfigurationMaster> TblConfigurationMasters { get; set; } = new List<TblConfigurationMaster>();
}