// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class TblFicciRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDelete { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? LastUpdateOn { get; set; }

    public int CreatedBy { get; set; }

    public int LastUpdateBy { get; set; }

    public bool? IsAdmin { get; set; }

    public virtual ICollection<FicciImum> FicciImums { get; set; } = new List<FicciImum>();
}