// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class Userloginlog
{
    public int UserLoginLogId { get; set; }

    public string LoginId { get; set; }

    public DateTime? LoginDate { get; set; }

    public string JwtToken { get; set; }

    public bool? LoginStatus { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string RefreshToken { get; set; }
}